require: rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
    - client/**/*
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Rails:
  Enabled: true

Style/Documentation:
  Exclude:
    - 'spec/**/*'

ModuleLength:
  Exclude:
    - spec/**/*'

BlockLength:
  Exclude:
    - spec/**/*

MethodLength:
  Exclude:
    - spec/**/*

StringLiterals:
  EnforcedStyle: double_quotes
